### ISSUE TITLE
customization

### ISSUE THREAD

**Issue by brianlangay4** [MannaYang/Flutter-ChatGPT#1]
"Hello! I recently stumbled upon a repository that's truly impressive - it's well-designed, straightforward, and boasts a stable, perfect architecture. I have a model from Hugging Face that I'd like to integrate for responses, replacing the current ChatGPT model. I've created server and client files to interact with this model, setting up an API to retrieve responses.

However, I lack experience in Dart, and I'd greatly appreciate some guidance on incorporating this model into the existing project. I'll provide the necessary server and client files. Any assistance you can offer would be  appreciated ."

[ProjectTom.zip](https://github.com/MannaYang/Flutter-ChatGPT/files/13325376/ProjectTom.zip)

帮助我大哥。

**Comment by MannaYang** [comment]
Hello did you running [backend] module successfully ? 

If you want to run your own model , add your generate text method into [backend] module main.py , then define the method api path or replace one of path to test it , the FastApi docs can test it easily. When you test it successfully , you can run [frontend] module . You should use EventSourceResponse   to return streaming text , if just async generate text and return , also see [main.py - @app.get("/api/llm/v1/file/vector/list"] .

With your zip file  , i see LLM model : [oasst-sft-4-pythia-12b-epoch-3.5](https://huggingface.co/OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5) , please read it doc and test.
@brianlangay4

**Comment by brianlangay4** [comment]
yes  i was able to run project successfull its fantastic 
and for the customiization i will give try to make this modification i will let you know if i stuck somewhere youre the best thanks for the tip and this amaizing project. 👏👏👏👏👏👏👏

**Comment by MannaYang** [comment]
@brianlangay4 I have pushed the latest version v2.0.0, current comment will be closed.
